#!/usr/bin/env python3

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.cm import get_cmap
from matplotlib.colors import SymLogNorm, LogNorm
from matplotlib.ticker import FuncFormatter, LogFormatterMathtext
from matplotlib.transforms import blended_transform_factory as trmix

import numpy as np

import math
import argparse
import os
import json
import warnings
from enum import Enum

class _trkpar(Enum):
    d0 = (0, r'$d_0$', 'mm')
    z0 = (1, r'$z_0$', 'mm')
    phi= (2, r'$\phi$', 'rad')
    theta = (3, r'$\theta$', 'rad')
    qoverp = (4, r'$q/p$', r'MeV$^{-1}$')
    def __init__(self, index, string, units):
        self.index = index
        self.string = string
        self.units = units
    # def __len__(self):
    #     return len(__class__.__members__)


def _get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file')
    parser.add_argument('output_dir', nargs='?', default='tracking')
    args = parser.parse_args()
    return args

def run():
    warnings.simplefilter("error")
    args = _get_args()
    with open(args.input_file, 'r') as jfile:
        jdict = json.load(jfile)

    cov_pars = _int_keys(jdict['cov'])
    mean_pars = _int_keys(jdict['mean'])
    _print_cor_matrix(cov_pars, 2, 2, output_dir=args.output_dir)
    for par in [_trkpar.d0, _trkpar.z0, _trkpar.phi, _trkpar.theta, _trkpar.qoverp]:
        cov = _get_par_eta_vs_pt(cov_pars, _variance_grabber(par))
        _print_par_eta_vs_pt(cov, output_dir=args.output_dir,
                             parameter=par, moment='width')
        mean = _get_par_eta_vs_pt(mean_pars, _mean_grabber(par))
        _print_par_eta_vs_pt(mean, output_dir=args.output_dir,
                             parameter=par, moment='mean')

_pt_bins = dict(enumerate([10, 20, 50, 100, 200, 250, 500, 750, 1000]))
# pt bins start at -1 so we can account for the lowest (dummy) one
_pt_bins[-1] = 0

_bonus = [3.0] #+ [3.2, 3.4, 3.6] # totally made up eta bins
_eta_bins = dict(enumerate(
    [0.0, 0.4, 0.8, 1.05, 1.5, 1.7, 2.0, 2.25, 2.7] + _bonus))

def _int_keys(json_dict):
    """recursive translation to int keyed dict"""
    try:
        odict = {int(k): _int_keys(v) for k,v in json_dict.items()}
    except AttributeError:
        return json_dict
    return odict

def _label_ticks(axis, labels=_trkpar):
    tickpos = np.linspace(0, len(labels) - 1, len(labels))
    axis.set_ticks(tickpos)
    axis.set_ticklabels([x.string for x in labels])

def _get_sym_ticks(lin_order):
    """get symmetric tickmarks for log scale around zero, up to 1"""
    major = 0.1**np.r_[1:lin_order + 1]
    mdiv = np.r_[2:10]
    minor = (mdiv.T * major[:,None]).flatten()
    both = np.sort(np.r_[major, minor])
    full_ticks = np.r_[-1, -both[::-1], 0, both, 1]
    return full_ticks

def _print_cor_matrix(matlist, pt_bin, eta_bin, output_dir):
    ar = np.asarray(matlist[pt_bin][eta_bin])
    invstdev = np.matrix(np.diag(np.diag(ar)**(-0.5)))
    cov = invstdev * ar * invstdev
    fig = Figure(figsize=(5.0, 5.0*3/4))
    canvas = FigureCanvas(fig)
    ax = fig.add_subplot(1,1,1)
    cmap = get_cmap('RdBu')
    lin_order = 3               # make log flat after this order of small
    norm = SymLogNorm(linthresh=10**(-lin_order), vmin=-1.001, vmax=1-0.001)
    img = ax.matshow(np.asarray(cov), norm=norm, cmap=cmap)
    # cmap.set_over('k')
    _label_ticks(ax.xaxis)
    _label_ticks(ax.yaxis)
    full_ticks = _get_sym_ticks(lin_order)
    formatter = FuncFormatter(_log_formatting)
    cb = fig.colorbar(img, label='Correlation Coefficient', ticks=full_ticks,
                      format=formatter)
    outname = 'cor_mat_ptbin{}_etabin{}.pdf'.format(pt_bin, eta_bin)
    if not os.path.isdir(output_dir):
        os.mkdir(output_dir)
    canvas.print_figure(os.path.join(output_dir,outname), bbox_inches='tight')


def _print_par_eta_vs_pt(array, output_dir, parameter, moment='width'):
    fig = Figure(figsize=(5.0, 5.0*3/4))
    canvas = FigureCanvas(fig)
    ax = fig.add_subplot(1,1,1)
    zeroed_pt = np.sort(np.fromiter(_pt_bins.values(), dtype='d'))
    zeroed_eta = np.sort(np.fromiter(_eta_bins.values(), dtype='d'))
    masked = np.ma.masked_invalid(array)
    cmap = get_cmap('jet')
    cmap.set_bad('k')
    img = ax.pcolormesh(zeroed_pt, zeroed_eta, masked.T, cmap=cmap)
    lab = parameter.string + ' ' + moment
    units = parameter.units
    if units:
        lab += ' [{}]'.format(units)
    cb = fig.colorbar(img, label=lab)
    ax.set_xscale('log')
    ax.set_xlim(5, zeroed_pt[-1])
    ax.set_ylim(zeroed_eta[0], zeroed_eta[-1])
    ax.set_xlabel(r'$p_{\rm T}$ [GeV]', x=0.98, ha='right')
    ax.set_ylabel(r'$|\eta|$', y=0.98, ha='right')

    badx = 10
    ax.axvline(x=badx, color='r')
    textopt = dict(
        transform=trmix(ax.transData, ax.transAxes), ha='right', y=0.5,
        rotation='vertical', va='center')
    ax.text(x=badx, s='not defined', color='red', **textopt)

    outname = '{}_{}_eta_vs_pt.pdf'.format(parameter.name, moment)
    if not os.path.isdir(output_dir):
        os.mkdir(output_dir)
    canvas.print_figure(os.path.join(output_dir,outname), bbox_inches='tight')

# define `grabber' functions to get various stuff from cov / mean lists
def _variance_grabber(parameter):
    idx = parameter.index
    def grabber(parlist):
        return (parlist[idx][idx])**0.5
    return grabber

def _mean_grabber(parameter):
    idx = parameter.index
    def grabber(parlist):
        return parlist[idx]
    return grabber

def _get_par_eta_vs_pt(cov_pars, grabber):
    n_pt = len(_pt_bins)    # extra pt bin is dummy at low end
    n_eta = len(_eta_bins) - 1
    pt_eta_array = np.ones((n_pt, n_eta)) * float('nan')
    # we don't have values for the upper bin: it's just a dummy to indicate
    # higher values.
    for pt_bin, pt_upper in sorted(_pt_bins.items())[:-1]:
        for eta_bin, eta_upper in sorted(_eta_bins.items())[:-1]:
            # we pull the -1 bin from the 0 bin...
            pt_eta_list = cov_pars[max(pt_bin, 0)].get(eta_bin)
            if not pt_eta_list: continue
            pt_eta_array[pt_bin + 1, eta_bin] = grabber(pt_eta_list)
    return pt_eta_array

# ________________________________________________________________________

def _log_formatting(value, pos):
    if value == 0:
        return r'0'
    roundlog = round(math.log(abs(value), 10))
    roundval = 10**roundlog
    if not np.isclose(roundval, abs(value)):
        return ''
    if np.isclose(roundval, 0.1):
        return r'0.1'
    if roundval == 1:
        base = math.copysign(1, value)
        exp = ''
    elif roundval == 10:
        base = math.copysign(10, value)
        exp = ''
    else:
        base = math.copysign(10, value)
        exp = round(math.log(abs(value),10))
    return r'{:.0f}$^{{\mathdefault{{ {} }} }}$'.format(base, exp)

if __name__ == '__main__':
    run()

