#!/usr/bin/env python3

import os, sys
import numpy as np
from h5py import File
import argparse

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.colors import LogNorm
from delphes.plotutils import Hist, is_h5_hist
from delphes.mplutils import Canvas, draw2d, draw1d
from delphes.colors import flavor_colors

def _get_args():
    d = 'default: %(default)s'
    c = 'const: %(const)s'
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file')
    parser.add_argument('output_dir', nargs='?', default='spectra', help=d)
    parser.add_argument('-e', '--ext', default='.pdf', help=d)
    parser.add_argument('-l', '--log', action='store_true')
    args = parser.parse_args()
    return args



def run():
    args = _get_args()
    hists_by_var = {
        "jet_pt":[],
        "n_primary_tracks":[],
        "n_secondary_vertices":[],
        "n_tracks_in_secondary":[]}
    with File(args.input_file, 'r') as h5:
        for flavor, plots in h5['jet_vars'].items():
            for var, hists in hists_by_var.items():
                hist = Hist(plots[var])
                hist.label = flavor
                hist.color = flavor_colors[flavor]
                hists.append(hist)

    def oname(base):
        return os.path.join(args.output_dir, base + args.ext)
    for var in hists_by_var:
        with Canvas(oname(var)) as can:
            draw1d(can, hists_by_var[var], log=args.log)


if __name__ == '__main__':
    run()
