#!/usr/bin/env python3


import os, sys
import numpy as np
from h5py import File
import argparse

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.colors import LogNorm
from delphes.plotutils import Hist, is_h5_hist
from delphes.mplutils import Canvas, draw2d, draw1d

def _get_args():
    d = 'default: %(default)s'
    c = 'const: %(const)s'
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file')
    parser.add_argument('output_dir', nargs='?', default='smearing', help=d)
    parser.add_argument('-e', '--ext', default='.pdf', help=d)
    args = parser.parse_args()
    return args

def run():
    args = _get_args()

    # load histograms
    hists1 = {}
    hists2 = {}
    with File(args.input_file, 'r') as h5:
        for name, dataset in h5['all']['delphes'].items():
            hist = Hist(dataset)
            if len(hist.axes) == 1:
                hists1[name] = hist
            elif len(hist.axes) == 2:
                hists2[name] = hist

    def outnm(name):
        out = os.path.join(args.output_dir, '{}.pdf'.format(name))
        print('drawing {}'.format(out))
        return out
    # draw 2d
    for name, hist in hists2.items():
        with Canvas(outnm(name)) as can:
            draw2d(can, hist)
    # draw 1d
    for name, hist in hists1.items():
        with Canvas(outnm(name)) as can:
            draw1d(can, [hist])

if __name__ == '__main__':
    run()
