labels = {
    'jetProb': 'JetProb',
    'lsig': 'SV sig',
    'track2d0sig': r'2nd $S_{d_0}$',
    'track3d0sig': r'3rd $S_{d_0}$',
    'drjet': r'$\Delta R(\mathrm{jet}, \mathrm{vx})$',
    'efrc': r'Sec Vx Energy Fraction',
    'efrac': r'Sec Vx Energy Fraction',
    'mass': r'Vertex Mass',
    'n_sig_track': r'$n$ track $S_{L} > 1.8$',
    'n_vx_track': r'$n$ Vx Matched Tracks',
    'nsecvtx': r'$n$ Secondary Vertex',
    'width_eta': r'width $\eta$',
    'width_phi': r'width $\phi$',
    'dphi': r'$\Delta \phi(\mathrm{jet}, \mathrm{vx})$',
    'drvj': r'$\Delta R(\mathrm{jet}, \mathrm{vx})$',
    'eta': r'$\eta$',
    'lxy': r'$L_{xy}$',
    'ntrk': r'$n$ tracks',
    'nvtx': r'$n$ vertices in jet',
    'pt': r'Jet $p_{\mathrm{T}}$',
    'vxn': r'Vertex Number',
    'julian_hl': r'Julian HL',
}
